//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17nsj.DataAccess
{
    using System;
    using System.Collections.Generic;

    public partial class JamGoods
    {
        public string Category { get; set; }
        public int Id { get; set; }
        public int DisplayOrder { get; set; }
        public string ThumbnailURL { get; set; }
        public string DetailImageURL { get; set; }
        public int Stock { get; set; }
        public System.DateTime StockUpdatedAt { get; set; }
        public string PartsNumber { get; set; }
        public string GoodsName { get; set; }
        public int Price { get; set; }
        public string Size { get; set; }
        public string Description { get; set; }
        public bool IsAvailable { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    }
}
